"""
Seeds 20 realistic test escort accounts into the local database.
Run inside the backend container:
  docker compose exec backend python seed_test_escorts.py
"""
import asyncio
import sys
from sqlalchemy import select
from app.database import AsyncSessionLocal
from app.models.escort import Escort, EscortService
from app.models.borough import Borough
from app.utils.security import hash_password
from app.utils.slugify import make_slug, make_unique_slug

PASSWORD = "TestPass123!"   # same password for every test account

ESCORTS = [
    {
        "stage_name": "Alessia",
        "email": "alessia@test.bluechips",
        "age": 24,
        "nationality": "Italian",
        "ethnicity": "White European",
        "height_cm": 168,
        "build": "slim",
        "hair_colour": "Brunette",
        "eye_colour": "Brown",
        "dress_size": "8",
        "chest": "34B",
        "borough": "mayfair",
        "availability_type": "both",
        "rate_30min": 150, "rate_1hour": 250, "rate_2hours": 450, "rate_overnight": 1200,
        "about_me": "Sophisticated Italian companion with a passion for fine dining and intelligent conversation. Whether you want a romantic dinner date or a relaxing private encounter, I will make every moment unforgettable.",
        "languages": ["English", "Italian", "French"],
        "booking_notice": "2 hours notice preferred",
        "std_tested": True,
        "std_tested_date": "2025-03",
        "subscription_tier": "elite",
        "verification_level": 3,
        "available_now": True,
        "services": ["GFE", "DFK", "69", "Massage", "Dinner Date", "Overnight"],
    },
    {
        "stage_name": "Yuki",
        "email": "yuki@test.bluechips",
        "age": 22,
        "nationality": "Japanese",
        "ethnicity": "East Asian",
        "height_cm": 158,
        "build": "petite",
        "hair_colour": "Black",
        "eye_colour": "Brown",
        "dress_size": "6",
        "chest": "32A",
        "borough": "chelsea",
        "availability_type": "incall",
        "rate_30min": 120, "rate_1hour": 200, "rate_2hours": 350, "rate_overnight": 900,
        "about_me": "Sweet and playful Japanese companion based in Chelsea. I offer a genuinely warm and intimate GFE experience. I love making my clients feel completely at ease from the moment we meet.",
        "languages": ["English", "Japanese"],
        "booking_notice": "1 hour notice",
        "std_tested": True,
        "std_tested_date": "2025-02",
        "subscription_tier": "premium",
        "verification_level": 2,
        "available_now": False,
        "services": ["GFE", "Massage", "Erotic Massage", "DFK", "Tantric Massage", "69"],
    },
    {
        "stage_name": "Natasha",
        "email": "natasha@test.bluechips",
        "age": 27,
        "nationality": "Russian",
        "ethnicity": "White European",
        "height_cm": 172,
        "build": "slim",
        "hair_colour": "Blonde",
        "eye_colour": "Blue",
        "dress_size": "8",
        "chest": "34C",
        "borough": "kensington",
        "availability_type": "both",
        "rate_30min": 200, "rate_1hour": 350, "rate_2hours": 600, "rate_overnight": 1500,
        "about_me": "Tall, elegant Russian model companion living in Kensington. I am cultured, well-travelled and speak four languages. Available for upscale social engagements and private meetings.",
        "languages": ["English", "Russian", "German", "French"],
        "booking_notice": "3 hours notice",
        "std_tested": True,
        "std_tested_date": "2025-04",
        "subscription_tier": "elite",
        "verification_level": 3,
        "available_now": True,
        "services": ["GFE", "PSE", "DFK", "69", "OWO", "Dinner Date", "Travel Companion", "Overnight"],
    },
    {
        "stage_name": "Camila",
        "email": "camila@test.bluechips",
        "age": 25,
        "nationality": "Brazilian",
        "ethnicity": "Latin / Hispanic",
        "height_cm": 165,
        "build": "curvy",
        "hair_colour": "Brunette",
        "eye_colour": "Brown",
        "dress_size": "10",
        "chest": "36D",
        "borough": "shoreditch",
        "availability_type": "both",
        "rate_30min": 100, "rate_1hour": 180, "rate_2hours": 300, "rate_overnight": 800,
        "about_me": "Passionate Brazilian beauty with natural curves and a warm personality. I love what I do and it shows! My energy is infectious and I guarantee you will leave with a smile.",
        "languages": ["English", "Portuguese", "Spanish"],
        "booking_notice": "Same day OK",
        "std_tested": True,
        "std_tested_date": "2025-01",
        "subscription_tier": "premium",
        "verification_level": 2,
        "available_now": True,
        "services": ["GFE", "PSE", "OWO", "DFK", "69", "COB", "Striptease", "Lap Dance"],
    },
    {
        "stage_name": "Priya",
        "email": "priya@test.bluechips",
        "age": 26,
        "nationality": "Indian",
        "ethnicity": "South Asian",
        "height_cm": 163,
        "build": "curvy",
        "hair_colour": "Black",
        "eye_colour": "Dark Brown",
        "dress_size": "10",
        "chest": "36C",
        "borough": "canary-wharf",
        "availability_type": "incall",
        "rate_30min": 100, "rate_1hour": 180, "rate_2hours": 300, "rate_overnight": 750,
        "about_me": "Exotic Indian companion offering a truly sensual experience. Educated, sophisticated and very open-minded. I enjoy meeting successful gentlemen looking for something special beyond the ordinary.",
        "languages": ["English", "Hindi", "Punjabi"],
        "booking_notice": "2 hours preferred",
        "std_tested": True,
        "std_tested_date": "2025-03",
        "subscription_tier": "essential",
        "verification_level": 2,
        "available_now": False,
        "services": ["GFE", "Massage", "Tantric Massage", "Erotic Massage", "DFK", "Role Play"],
    },
    {
        "stage_name": "Sofia",
        "email": "sofia@test.bluechips",
        "age": 23,
        "nationality": "Spanish",
        "ethnicity": "White European",
        "height_cm": 166,
        "build": "slim",
        "hair_colour": "Dark Brown",
        "eye_colour": "Hazel",
        "dress_size": "8",
        "chest": "34B",
        "borough": "notting-hill",
        "availability_type": "both",
        "rate_30min": 120, "rate_1hour": 200, "rate_2hours": 360, "rate_overnight": 950,
        "about_me": "Fun-loving Spanish companion based in Notting Hill. I have a fiery personality balanced with warmth and genuine care for my clients. Incall at my stylish private flat or I can visit you.",
        "languages": ["English", "Spanish"],
        "booking_notice": "1 hour notice",
        "std_tested": False,
        "subscription_tier": "essential",
        "verification_level": 1,
        "available_now": True,
        "services": ["GFE", "DFK", "69", "OWO", "Striptease", "Toys"],
    },
    {
        "stage_name": "Zara",
        "email": "zara@test.bluechips",
        "age": 29,
        "nationality": "Nigerian",
        "ethnicity": "Black African",
        "height_cm": 170,
        "build": "curvy",
        "hair_colour": "Black",
        "eye_colour": "Brown",
        "dress_size": "12",
        "chest": "38DD",
        "borough": "brixton",
        "availability_type": "both",
        "rate_30min": 80, "rate_1hour": 150, "rate_2hours": 260, "rate_overnight": 650,
        "about_me": "Stunning West African queen with natural curves that will take your breath away. I am bubbly, genuine and great fun to be around. Whether it is a quick visit or a longer booking, I bring my full self every time.",
        "languages": ["English", "Yoruba"],
        "booking_notice": "30 mins notice OK",
        "std_tested": True,
        "std_tested_date": "2025-02",
        "subscription_tier": "essential",
        "verification_level": 2,
        "available_now": True,
        "services": ["GFE", "OWO", "DFK", "69", "COB", "PSE"],
    },
    {
        "stage_name": "Lena",
        "email": "lena@test.bluechips",
        "age": 24,
        "nationality": "Polish",
        "ethnicity": "White European",
        "height_cm": 169,
        "build": "slim",
        "hair_colour": "Blonde",
        "eye_colour": "Green",
        "dress_size": "8",
        "chest": "34C",
        "borough": "hammersmith",
        "availability_type": "outcall",
        "rate_30min": None, "rate_1hour": 160, "rate_2hours": 280, "rate_overnight": 700,
        "about_me": "Pretty Polish girl available for outcalls across London. I am naturally friendly and easy to talk to, which makes our time together feel relaxed and natural. Discretion is always guaranteed.",
        "languages": ["English", "Polish"],
        "booking_notice": "2 hours notice",
        "std_tested": True,
        "std_tested_date": "2024-12",
        "subscription_tier": "free",
        "verification_level": 1,
        "available_now": False,
        "services": ["GFE", "DFK", "Massage", "Dinner Date"],
    },
    {
        "stage_name": "Amara",
        "email": "amara@test.bluechips",
        "age": 28,
        "nationality": "Kenyan",
        "ethnicity": "Black African",
        "height_cm": 173,
        "build": "athletic",
        "hair_colour": "Black",
        "eye_colour": "Brown",
        "dress_size": "10",
        "chest": "36B",
        "borough": "stratford",
        "availability_type": "both",
        "rate_30min": 80, "rate_1hour": 140, "rate_2hours": 240, "rate_overnight": 600,
        "about_me": "Athletic Kenyan beauty with long legs and a bright smile. I keep myself extremely fit and healthy. Clean, discreet and always punctual. My flat is private and welcoming.",
        "languages": ["English", "Swahili"],
        "booking_notice": "1 hour notice",
        "std_tested": True,
        "std_tested_date": "2025-01",
        "subscription_tier": "free",
        "verification_level": 1,
        "available_now": False,
        "services": ["GFE", "Erotic Massage", "DFK", "69"],
    },
    {
        "stage_name": "Diana",
        "email": "diana@test.bluechips",
        "age": 31,
        "nationality": "Romanian",
        "ethnicity": "White European",
        "height_cm": 167,
        "build": "curvy",
        "hair_colour": "Red",
        "eye_colour": "Green",
        "dress_size": "10",
        "chest": "36D",
        "borough": "paddington",
        "availability_type": "incall",
        "rate_30min": 100, "rate_1hour": 175, "rate_2hours": 300, "rate_overnight": 800,
        "about_me": "Natural redhead with an hourglass figure and a wicked sense of humour. Six years experience — I know exactly how to please and what a real gentleman needs. Come and find out for yourself.",
        "languages": ["English", "Romanian", "Italian"],
        "booking_notice": "1 hour notice",
        "std_tested": True,
        "std_tested_date": "2025-04",
        "subscription_tier": "premium",
        "verification_level": 2,
        "available_now": True,
        "services": ["GFE", "PSE", "OWO", "OWO-CIM", "DFK", "69", "Anal", "BDSM", "Role Play"],
    },
    {
        "stage_name": "Mei",
        "email": "mei@test.bluechips",
        "age": 21,
        "nationality": "Chinese",
        "ethnicity": "East Asian",
        "height_cm": 155,
        "build": "petite",
        "hair_colour": "Black",
        "eye_colour": "Brown",
        "dress_size": "6",
        "chest": "32B",
        "borough": "soho",
        "availability_type": "incall",
        "rate_30min": 100, "rate_1hour": 180, "rate_2hours": 300, "rate_overnight": 700,
        "about_me": "Delicate and attentive Chinese companion in the heart of Soho. I am very passionate and love providing full body massage followed by the most intimate attention. Repeat clients always welcome.",
        "languages": ["English", "Mandarin", "Cantonese"],
        "booking_notice": "30 mins notice OK",
        "std_tested": True,
        "std_tested_date": "2025-03",
        "subscription_tier": "premium",
        "verification_level": 2,
        "available_now": True,
        "services": ["Massage", "Erotic Massage", "Tantric Massage", "Happy Ending", "GFE", "DFK"],
    },
    {
        "stage_name": "Isabella",
        "email": "isabella@test.bluechips",
        "age": 26,
        "nationality": "Colombian",
        "ethnicity": "Latin / Hispanic",
        "height_cm": 162,
        "build": "curvy",
        "hair_colour": "Brunette",
        "eye_colour": "Brown",
        "dress_size": "10",
        "chest": "36DD",
        "borough": "westminster",
        "availability_type": "both",
        "rate_30min": 120, "rate_1hour": 200, "rate_2hours": 350, "rate_overnight": 900,
        "about_me": "Colombian temptress with natural curves and fire in her soul. Former dancer with a body that speaks for itself. I bring passion and energy to every encounter and love clients who appreciate a real woman.",
        "languages": ["English", "Spanish"],
        "booking_notice": "2 hours notice",
        "std_tested": True,
        "std_tested_date": "2025-02",
        "subscription_tier": "elite",
        "verification_level": 3,
        "available_now": True,
        "services": ["GFE", "PSE", "OWO", "DFK", "69", "COB", "Striptease", "Lap Dance", "Duo"],
    },
    {
        "stage_name": "Aisha",
        "email": "aisha@test.bluechips",
        "age": 27,
        "nationality": "Moroccan",
        "ethnicity": "Middle Eastern / Arab",
        "height_cm": 165,
        "build": "slim",
        "hair_colour": "Black",
        "eye_colour": "Dark Brown",
        "dress_size": "8",
        "chest": "34C",
        "borough": "bayswater",
        "availability_type": "incall",
        "rate_30min": 120, "rate_1hour": 200, "rate_2hours": 350, "rate_overnight": 900,
        "about_me": "Mysterious and alluring Moroccan companion offering a unique North African experience. Educated and culturally rich, I enjoy deep conversations as much as physical intimacy. Absolute discretion assured.",
        "languages": ["English", "Arabic", "French"],
        "booking_notice": "2 hours notice",
        "std_tested": True,
        "std_tested_date": "2025-01",
        "subscription_tier": "premium",
        "verification_level": 2,
        "available_now": False,
        "services": ["GFE", "DFK", "Massage", "Erotic Massage", "Dinner Date", "Role Play"],
    },
    {
        "stage_name": "Jade",
        "email": "jade@test.bluechips",
        "age": 23,
        "nationality": "British",
        "ethnicity": "Mixed Race",
        "height_cm": 164,
        "build": "slim",
        "hair_colour": "Brunette",
        "eye_colour": "Hazel",
        "dress_size": "8",
        "chest": "34B",
        "borough": "hackney",
        "availability_type": "both",
        "rate_30min": 80, "rate_1hour": 150, "rate_2hours": 260, "rate_overnight": 650,
        "about_me": "Mixed race British girl born and raised in London. I am natural, real and totally genuine — no fake photos or surprises. Love meeting new people. Available most evenings and weekends.",
        "languages": ["English"],
        "booking_notice": "1 hour notice",
        "std_tested": False,
        "subscription_tier": "free",
        "verification_level": 1,
        "available_now": True,
        "services": ["GFE", "DFK", "OWO", "69", "Toys"],
    },
    {
        "stage_name": "Valentina",
        "email": "valentina@test.bluechips",
        "age": 30,
        "nationality": "Argentine",
        "ethnicity": "Latin / Hispanic",
        "height_cm": 170,
        "build": "athletic",
        "hair_colour": "Brunette",
        "eye_colour": "Brown",
        "dress_size": "8",
        "chest": "34C",
        "borough": "islington",
        "availability_type": "outcall",
        "rate_30min": None, "rate_1hour": 200, "rate_2hours": 360, "rate_overnight": 950,
        "about_me": "Argentine professional with a toned physique and a sophisticated personality. I am available for upmarket outcalls, corporate events and travel companionship across Europe. References available.",
        "languages": ["English", "Spanish", "Italian"],
        "booking_notice": "4 hours notice",
        "std_tested": True,
        "std_tested_date": "2025-04",
        "subscription_tier": "elite",
        "verification_level": 3,
        "available_now": False,
        "services": ["GFE", "DFK", "Dinner Date", "Travel Companion", "Overnight", "Couples Welcome"],
    },
    {
        "stage_name": "Tanya",
        "email": "tanya@test.bluechips",
        "age": 33,
        "nationality": "Ukrainian",
        "ethnicity": "White European",
        "height_cm": 171,
        "build": "slim",
        "hair_colour": "Blonde",
        "eye_colour": "Blue",
        "dress_size": "8",
        "chest": "36C",
        "borough": "city-of-london",
        "availability_type": "both",
        "rate_30min": 150, "rate_1hour": 250, "rate_2hours": 450, "rate_overnight": 1100,
        "about_me": "Mature, experienced Ukrainian companion catering to discerning City gentlemen. Former finance professional — I understand the pressures of your world and provide the perfect escape. Upscale incall near Bank.",
        "languages": ["English", "Ukrainian", "Russian"],
        "booking_notice": "2 hours notice",
        "std_tested": True,
        "std_tested_date": "2025-03",
        "subscription_tier": "elite",
        "verification_level": 3,
        "available_now": True,
        "services": ["GFE", "OWO", "DFK", "69", "Dinner Date", "Overnight", "BDSM", "Domination"],
    },
    {
        "stage_name": "Monique",
        "email": "monique@test.bluechips",
        "age": 28,
        "nationality": "French",
        "ethnicity": "Black Caribbean",
        "height_cm": 168,
        "build": "curvy",
        "hair_colour": "Black",
        "eye_colour": "Brown",
        "dress_size": "12",
        "chest": "38D",
        "borough": "lambeth",
        "availability_type": "both",
        "rate_30min": 90, "rate_1hour": 160, "rate_2hours": 280, "rate_overnight": 700,
        "about_me": "French Caribbean beauty with a smooth caramel complexion and natural curves. Bilingual, educated and genuinely warm. I pride myself on making every client feel special and completely comfortable.",
        "languages": ["English", "French"],
        "booking_notice": "1 hour notice",
        "std_tested": True,
        "std_tested_date": "2025-02",
        "subscription_tier": "essential",
        "verification_level": 2,
        "available_now": False,
        "services": ["GFE", "DFK", "OWO", "69", "Erotic Massage", "COB"],
    },
    {
        "stage_name": "Sasha",
        "email": "sasha@test.bluechips",
        "age": 25,
        "nationality": "Czech",
        "ethnicity": "White European",
        "height_cm": 172,
        "build": "slim",
        "hair_colour": "Brunette",
        "eye_colour": "Green",
        "dress_size": "8",
        "chest": "34B",
        "borough": "fulham",
        "availability_type": "incall",
        "rate_30min": 100, "rate_1hour": 180, "rate_2hours": 300, "rate_overnight": 750,
        "about_me": "Long-legged Czech model living in Fulham. I am elegant and refined with a playful side that comes out once we are comfortable together. My private flat is clean, luxurious and completely discreet.",
        "languages": ["English", "Czech", "Slovak"],
        "booking_notice": "1 hour notice",
        "std_tested": True,
        "std_tested_date": "2025-01",
        "subscription_tier": "premium",
        "verification_level": 2,
        "available_now": True,
        "services": ["GFE", "PSE", "OWO", "DFK", "69", "Deep Throat", "Anal", "Toys"],
    },
    {
        "stage_name": "Layla",
        "email": "layla@test.bluechips",
        "age": 26,
        "nationality": "Lebanese",
        "ethnicity": "Middle Eastern / Arab",
        "height_cm": 164,
        "build": "curvy",
        "hair_colour": "Dark Brown",
        "eye_colour": "Brown",
        "dress_size": "10",
        "chest": "36C",
        "borough": "marylebone",
        "availability_type": "both",
        "rate_30min": 130, "rate_1hour": 220, "rate_2hours": 400, "rate_overnight": 1000,
        "about_me": "Gorgeous Lebanese companion with smouldering looks and an addictive personality. I am sensual, generous and genuinely enjoy what I do. Based near Marylebone — central and easy to reach.",
        "languages": ["English", "Arabic", "French"],
        "booking_notice": "2 hours notice",
        "std_tested": True,
        "std_tested_date": "2025-04",
        "subscription_tier": "premium",
        "verification_level": 2,
        "available_now": True,
        "services": ["GFE", "OWO", "DFK", "69", "Massage", "Erotic Massage", "Dinner Date"],
    },
    {
        "stage_name": "Chloe",
        "email": "chloe@test.bluechips",
        "age": 22,
        "nationality": "British",
        "ethnicity": "White British",
        "height_cm": 160,
        "build": "petite",
        "hair_colour": "Blonde",
        "eye_colour": "Blue",
        "dress_size": "6",
        "chest": "32B",
        "borough": "richmond",
        "availability_type": "both",
        "rate_30min": 80, "rate_1hour": 140, "rate_2hours": 240, "rate_overnight": 600,
        "about_me": "Sweet petite English girl from Richmond. I am naturally girly, very affectionate and completely genuine. New to the industry but very enthusiastic. Looking forward to meeting lovely gentlemen.",
        "languages": ["English"],
        "booking_notice": "Same day OK",
        "std_tested": False,
        "subscription_tier": "free",
        "verification_level": 1,
        "available_now": False,
        "services": ["GFE", "DFK", "Massage", "Striptease"],
    },
]


async def main():
    async with AsyncSessionLocal() as db:
        # Fetch all boroughs keyed by slug
        result = await db.execute(select(Borough))
        boroughs = {b.slug: b for b in result.scalars().all()}

        if not boroughs:
            print("ERROR: No boroughs found. Run the seed first: docker compose up (wait for seed log).")
            sys.exit(1)

        # Fetch existing slugs to avoid collisions
        slug_result = await db.execute(select(Escort.slug))
        existing_slugs = {row[0] for row in slug_result.fetchall()}

        created = 0
        skipped = 0
        for data in ESCORTS:
            # Skip if email already exists
            existing = await db.execute(select(Escort).where(Escort.email == data["email"]))
            if existing.scalar_one_or_none():
                print(f"  SKIP  {data['stage_name']} — already exists")
                skipped += 1
                continue

            borough = boroughs.get(data["borough"])
            if not borough:
                print(f"  WARN  Borough '{data['borough']}' not found for {data['stage_name']}, skipping borough")

            slug = make_unique_slug(data["stage_name"], existing_slugs)
            existing_slugs.add(slug)

            escort = Escort(
                email=data["email"],
                hashed_password=hash_password(PASSWORD),
                stage_name=data["stage_name"],
                slug=slug,
                age=data["age"],
                nationality=data["nationality"],
                ethnicity=data["ethnicity"],
                height_cm=data["height_cm"],
                build=data["build"],
                hair_colour=data["hair_colour"],
                eye_colour=data["eye_colour"],
                dress_size=data["dress_size"],
                chest=data["chest"],
                borough_id=borough.id if borough else None,
                availability_type=data["availability_type"],
                rate_30min=data.get("rate_30min"),
                rate_1hour=data.get("rate_1hour"),
                rate_2hours=data.get("rate_2hours"),
                rate_overnight=data.get("rate_overnight"),
                about_me=data["about_me"],
                languages=data["languages"],
                booking_notice=data["booking_notice"],
                std_tested=data["std_tested"],
                std_tested_date=data.get("std_tested_date"),
                verification_level=data["verification_level"],
                is_email_verified=True,
                is_active=True,
                is_approved=True,
                available_now=data["available_now"],
                profile_complete=True,
                subscription_tier=data["subscription_tier"],
            )
            db.add(escort)
            await db.flush()  # get escort.id

            for tag in data["services"]:
                db.add(EscortService(escort_id=escort.id, tag=tag))

            print(f"  OK    {data['stage_name']} ({data['ethnicity']}) — {data['subscription_tier']} — /{slug}")
            created += 1

        await db.commit()
        print(f"\nDone. {created} created, {skipped} skipped.")
        print(f"Login with any account using password: {PASSWORD}")


if __name__ == "__main__":
    asyncio.run(main())
