"""add_whatsapp_phone_bluetick_fields

Revision ID: 5252eaf02a13
Revises: 0001
Create Date: 2026-05-01 20:01:00.256297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5252eaf02a13'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_boosts_escort_id'), 'boosts', ['escort_id'], unique=False)
    op.drop_constraint('boroughs_slug_key', 'boroughs', type_='unique')
    op.drop_index('ix_boroughs_slug', table_name='boroughs')
    op.create_index(op.f('ix_boroughs_slug'), 'boroughs', ['slug'], unique=True)
    op.add_column('escorts', sa.Column('whatsapp_number', sa.String(length=30), nullable=True))
    op.add_column('escorts', sa.Column('phone_number', sa.String(length=30), nullable=True))
    op.add_column('escorts', sa.Column('blue_tick_active', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('escorts', sa.Column('blue_tick_stripe_subscription_id', sa.String(length=100), nullable=True))
    op.drop_constraint('escorts_email_key', 'escorts', type_='unique')
    op.drop_constraint('escorts_slug_key', 'escorts', type_='unique')
    op.drop_index('ix_escorts_email', table_name='escorts')
    op.create_index(op.f('ix_escorts_email'), 'escorts', ['email'], unique=True)
    op.drop_index('ix_escorts_slug', table_name='escorts')
    op.create_index(op.f('ix_escorts_slug'), 'escorts', ['slug'], unique=True)
    op.create_index(op.f('ix_subscriptions_escort_id'), 'subscriptions', ['escort_id'], unique=False)
    op.add_column('verifications', sa.Column('stripe_payment_intent_id', sa.String(length=100), nullable=True))
    op.add_column('verifications', sa.Column('stripe_charge_id', sa.String(length=100), nullable=True))
    op.add_column('verifications', sa.Column('refunded_at', sa.DateTime(), nullable=True))
    op.add_column('verifications', sa.Column('refund_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_verifications_escort_id'), 'verifications', ['escort_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verifications_escort_id'), table_name='verifications')
    op.drop_column('verifications', 'refund_id')
    op.drop_column('verifications', 'refunded_at')
    op.drop_column('verifications', 'stripe_charge_id')
    op.drop_column('verifications', 'stripe_payment_intent_id')
    op.drop_index(op.f('ix_subscriptions_escort_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_escorts_slug'), table_name='escorts')
    op.create_index('ix_escorts_slug', 'escorts', ['slug'], unique=False)
    op.drop_index(op.f('ix_escorts_email'), table_name='escorts')
    op.create_index('ix_escorts_email', 'escorts', ['email'], unique=False)
    op.create_unique_constraint('escorts_slug_key', 'escorts', ['slug'])
    op.create_unique_constraint('escorts_email_key', 'escorts', ['email'])
    op.drop_column('escorts', 'blue_tick_stripe_subscription_id')
    op.drop_column('escorts', 'blue_tick_active')
    op.drop_column('escorts', 'phone_number')
    op.drop_column('escorts', 'whatsapp_number')
    op.drop_index(op.f('ix_boroughs_slug'), table_name='boroughs')
    op.create_index('ix_boroughs_slug', 'boroughs', ['slug'], unique=False)
    op.create_unique_constraint('boroughs_slug_key', 'boroughs', ['slug'])
    op.drop_index(op.f('ix_boosts_escort_id'), table_name='boosts')
    # ### end Alembic commands ###
