import { useState, useEffect } from 'react'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { Loader2, Save, Crown, Users, PoundSterling, BadgeCheck } from 'lucide-react'
import toast from 'react-hot-toast'
import { AdminLayout } from './AdminLayout'
import { adminApi, FoundingOfferConfig } from '@/api/admin'

export function AdminFoundingOfferPage() {
  const qc = useQueryClient()
  const { data: cfg, isLoading } = useQuery({
    queryKey: ['admin-founding'],
    queryFn: adminApi.getFoundingOffer,
  })

  const [form, setForm] = useState<FoundingOfferConfig | null>(null)

  useEffect(() => {
    if (cfg) setForm(cfg)
  }, [cfg])

  const saveMutation = useMutation({
    mutationFn: (patch: Partial<FoundingOfferConfig>) => adminApi.updateFoundingOffer(patch),
    onSuccess: () => {
      toast.success('Founding offer updated')
      qc.invalidateQueries({ queryKey: ['admin-founding'] })
    },
    onError: (err: any) => toast.error(err?.response?.data?.detail ?? 'Update failed'),
  })

  if (isLoading || !form) {
    return (
      <AdminLayout>
        <div className="flex items-center justify-center py-20 text-stone-500">
          <Loader2 className="w-6 h-6 animate-spin" />
        </div>
      </AdminLayout>
    )
  }

  const setField = <K extends keyof FoundingOfferConfig>(key: K, value: FoundingOfferConfig[K]) => {
    setForm(f => f ? { ...f, [key]: value } : f)
  }

  const handleSave = () => {
    if (!form) return
    saveMutation.mutate({
      active: form.active,
      limit: form.limit,
      signups: form.signups,
      percent_off: form.percent_off,
      duration_months: form.duration_months,
      tier: form.tier,
      includes_blue_tick: form.includes_blue_tick,
      lifetime_discount_percent: form.lifetime_discount_percent,
      badge_label: form.badge_label,
    })
  }

  const remaining = Math.max(0, form.limit - form.signups)
  const percentFilled = form.limit > 0 ? Math.min(100, Math.round((form.signups / form.limit) * 100)) : 0

  return (
    <AdminLayout>
      <div className="space-y-6 max-w-3xl">
        <div>
          <h1 className="font-serif text-2xl text-ivory-100 flex items-center gap-2"><Crown className="w-5 h-5 text-gold-400" /> Founding Offer</h1>
          <p className="text-stone-500 text-sm mt-1">Configure the founding-member promotion. These values control the discount codes auto-generated by the Outreach CRM and the public landing page counter.</p>
        </div>

        {/* Status card */}
        <div className="bg-gradient-to-br from-gold-900/20 via-stone-900 to-stone-900 border border-gold-400/20 rounded-2xl p-6 space-y-4">
          <div className="flex items-start justify-between gap-4 flex-wrap">
            <div>
              <p className="text-xs uppercase tracking-widest text-gold-500 font-medium">Current status</p>
              <p className="font-serif text-3xl text-ivory-100 mt-1">{form.signups} / {form.limit}</p>
              <p className="text-stone-500 text-sm">{remaining} spots remaining · {form.active ? 'Live' : 'Hidden'}</p>
            </div>
            <label className="flex items-center gap-2 cursor-pointer">
              <span className="text-stone-400 text-sm">Active</span>
              <button
                type="button"
                onClick={() => setField('active', !form.active)}
                className={`relative w-11 h-6 rounded-full transition-colors ${form.active ? 'bg-gold-400' : 'bg-stone-700'}`}
              >
                <span className={`absolute top-0.5 w-5 h-5 rounded-full bg-black transition-transform ${form.active ? 'translate-x-5' : 'translate-x-0.5'}`} />
              </button>
            </label>
          </div>
          <div className="h-2 bg-stone-800 rounded-full overflow-hidden">
            <div className="h-full bg-gradient-to-r from-gold-500 to-gold-400 transition-all" style={{ width: `${percentFilled}%` }} />
          </div>
        </div>

        {/* Settings grid */}
        <div className="bg-stone-900 border border-surface-border rounded-xl p-6 space-y-6">
          <h2 className="font-serif text-lg text-ivory-100">Offer parameters</h2>

          <Field label="Limit (total founding spots)" hint="How many founders to accept before the offer closes.">
            <NumberInput value={form.limit} min={1} max={10000} onChange={v => setField('limit', v)} />
          </Field>

          <Field label="Signups (current)" hint="Auto-incremented when someone uses a founding code. Adjust manually only to correct mistakes.">
            <NumberInput value={form.signups} min={0} onChange={v => setField('signups', v)} />
          </Field>

          <div className="grid sm:grid-cols-2 gap-5">
            <Field label="Tier offered" hint="Which subscription tier the founding period unlocks.">
              <select
                value={form.tier}
                onChange={e => setField('tier', e.target.value)}
                className="w-full bg-surface border border-surface-border rounded-lg px-3 py-2 text-ivory-100 text-sm focus:outline-none focus:border-gold-400/60"
              >
                <option value="essential">Essential</option>
                <option value="premium">Premium</option>
                <option value="elite">Elite</option>
              </select>
            </Field>

            <Field label="Duration (months)" hint="How long the offer lasts after signup.">
              <NumberInput value={form.duration_months} min={1} max={24} onChange={v => setField('duration_months', v)} />
            </Field>

            <Field label="Discount % off" hint="100% = totally free for the duration. 50% = half off.">
              <NumberInput value={form.percent_off} min={1} max={100} onChange={v => setField('percent_off', v)} />
            </Field>

            <Field label="Lifetime discount % after period ends" hint="Permanent discount applied after the founding period concludes.">
              <NumberInput value={form.lifetime_discount_percent} min={0} max={100} onChange={v => setField('lifetime_discount_percent', v)} />
            </Field>
          </div>

          <Field label="Badge label" hint="Displayed on the escort's profile and dashboard.">
            <input
              value={form.badge_label}
              onChange={e => setField('badge_label', e.target.value)}
              maxLength={50}
              className="w-full bg-surface border border-surface-border rounded-lg px-3 py-2 text-ivory-100 text-sm focus:outline-none focus:border-gold-400/60"
            />
          </Field>

          <label className="flex items-center gap-3 cursor-pointer pt-2">
            <input
              type="checkbox"
              checked={form.includes_blue_tick}
              onChange={e => setField('includes_blue_tick', e.target.checked)}
              className="w-4 h-4 accent-gold-400"
            />
            <span className="text-ivory-200 text-sm">Include free Blue Tick verification</span>
          </label>
        </div>

        <div className="flex items-center justify-end gap-3">
          <a href="/admin/outreach" className="text-stone-500 hover:text-ivory-200 text-sm">Outreach CRM →</a>
          <button
            onClick={handleSave}
            disabled={saveMutation.isPending}
            className="flex items-center gap-2 px-5 py-2 rounded-lg bg-gold-400 text-black font-semibold text-sm hover:bg-gold-300 transition-colors disabled:opacity-60"
          >
            {saveMutation.isPending ? <Loader2 className="w-4 h-4 animate-spin" /> : <Save className="w-4 h-4" />}
            Save changes
          </button>
        </div>

        {/* Preview */}
        <div className="p-5 rounded-xl border border-stone-800 bg-stone-950 text-stone-500 text-xs leading-relaxed">
          <p className="mb-2"><strong className="text-stone-400">What this changes:</strong></p>
          <ul className="space-y-1 list-disc list-inside">
            <li>New <strong className="text-stone-300">FM-XXXXX</strong> codes generated in Outreach use these settings (existing codes keep their original terms)</li>
            <li>The <a href="/founding-50" className="text-gold-400 hover:text-gold-300">public landing page</a> reads these values for the counter and offer copy</li>
            <li>Generated DMs in Outreach use these terms in the message body</li>
            <li>When toggled off, the public page hides the counter and signups via founding codes are blocked</li>
          </ul>
        </div>
      </div>
    </AdminLayout>
  )
}

function Field({ label, hint, children }: { label: string; hint?: string; children: React.ReactNode }) {
  return (
    <div>
      <label className="block text-xs text-stone-400 mb-1.5 font-medium">{label}</label>
      {hint && <p className="text-stone-600 text-xs mb-2">{hint}</p>}
      {children}
    </div>
  )
}

function NumberInput({ value, min, max, onChange }: { value: number; min?: number; max?: number; onChange: (v: number) => void }) {
  return (
    <input
      type="number"
      value={value}
      min={min}
      max={max}
      onChange={e => onChange(Number(e.target.value))}
      className="w-full bg-surface border border-surface-border rounded-lg px-3 py-2 text-ivory-100 text-sm focus:outline-none focus:border-gold-400/60"
    />
  )
}
